# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-25 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0002_auto_20190221_0049'),
        ('wishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishes',
            name='wisher',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, related_name='made_wish', to='login_register.User'),
            preserve_default=False,
        ),
    ]
