# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-25 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0003_granted_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='granted',
            name='wisher',
        ),
    ]
