# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-26 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0002_auto_20190221_0049'),
        ('wishes', '0004_remove_granted_wisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='granted',
            name='grantor',
        ),
        migrations.RemoveField(
            model_name='like',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='like',
            name='wish_liked',
        ),
        migrations.AddField(
            model_name='wishes',
            name='granted_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='wishes',
            name='likes',
            field=models.ManyToManyField(related_name='liked', to='login_register.User'),
        ),
        migrations.DeleteModel(
            name='Granted',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
